#!/bin/sh

output() {
  retcode=$?
  if [ $retcode -eq 0 ]
    then echo "PASS: $test"
  elif [ $retcode -eq 77 ]
    then echo "SKIP: $test"
  else echo "FAIL: $test"
  fi
}

tst_items=$(find ${PWD}/tests/ -name 'test_*.py' -print)

# Run tests
for test in ${tst_items}
do
  pytest --color=no $test >/dev/null 2>&1
  output
done

exit 0
